#!/bin/bash
set -e

docker run --rm -it \
    --name 'homeassistant-satellite' \
    --device /dev/snd \
    --group-add=audio \
    --log-opt max-size=10m \
    --log-opt max-file=3 \
    'ghcr.io/synesthesiam/homeassistant-satellite:latest' "$@"
