#!/usr/bin/env python3
import sys
import subprocess
import venv
from pathlib import Path

_DIR = Path(__file__).parent
_PROGRAM_DIR = _DIR.parent
_VENV_DIR = _PROGRAM_DIR / ".venv"

try:
    context = venv.EnvBuilder().ensure_directories(_VENV_DIR)
    subprocess.check_call([context.env_exe, "-m", "sounddevice"] + sys.argv[1:])
except KeyboardInterrupt:
    pass
